name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zabbixagentwebhook:$(date +%s)
      working-directory: zabbix-webhook

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/someaveragedev/zabbixagentwebhook:latest
        docker run ghcr.io/someaveragedev/zabbixagentwebhook:latest
        docker push ghcr.io/someaveragedev/zabbixagentwebhook:latest
