name: Python FastAPI testing

on:
  push:
    branches: [ main ]


jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r zabbix-webhook/src/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=$PYTHONPATH:zabbix-webhook/src/app;pytest zabbix-webhook/src/app/tests/test_main.py

